name: Environment Variable Demo

on: [push]

env:
  GREETING: "Hi"

jobs:
  print-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "${{ env.GREETING }}, World!"
